name: front_end
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3 
  #flutter_secure_storage: ^9.2.4 #apropiat per guardar tokens de manera segura en plataformes mòbils, no funcionaper  webapps
  #Ús de mapes
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.4.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  file_selector: ^1.0.3

  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

