
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  django-web:
    build:
      context: ../back_end
    container_name: django-docker
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../back_end:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    env_file:
      - .env

  flutter-web:
    build:
      context: ../front_end            # Carpeta donde está el Dockerfile y el código Flutter
      dockerfile: Dockerfile           # Nombre del Dockerfile a usar para construir la imagen
    container_name: flutter-docker     # Nombre fijo para el contenedor
    ports:
      - "9000:9000"                    # Expone el puerto 9000 del contenedor al 9000 del host (para Flutter web)
    volumes:
      - ../front_end:/home/developer/app                    # Monta el código local dentro del contenedor para desarrollo en caliente
    working_dir: /home/developer/app    # Directorio de trabajo dentro del contenedor
    command: flutter run -d web-server --web-port=9000 --web-hostname=0.0.0.0  # Comando que se ejecuta al iniciar el contenedor (lanza Flutter web)
    depends_on:
      - django-web                     # Espera que el servicio django-web esté listo antes de iniciar este contenedor
    user: "1000:1000"                  # Ejecuta el contenedor con este UID:GID para evitar problemas de permisos
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Permite que el contenedor acceda al host usando el alias host.docker.internal
    environment:
      - ANDROID_ADB_SERVER_ADDRESS=host.docker.internal   # Indica que adb debe conectarse al host y no al contenedor
      - ANDROID_SDK_ROOT=/opt/android_sdk
      - ANDROID_HOME=/opt/android_sdk             # Alias para la variable ANDROID_SDK_ROOT, usado por algunas herramientas Android


volumes:
  postgres_data:
