services:
  db:
    image: postgres:17
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../postgres/db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"   # treu-ho si no el necessites fora docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  django-web:
    build:
      context: ../back_end
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../back_end:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  flutter-web:
    build:
      context: ../front_end
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ../front_end:/home/developer/app
      - flutter_pub_cache:/home/developer/.pub-cache
      # - android_sdk:/opt/android_sdk   # només si realment ho uses
      # - gradle_cache:/home/developer/.gradle  # només si realment ho uses
    working_dir: /home/developer/app
    command: sh -c "flutter pub get && flutter run -d web-server --web-port=9000 --web-hostname=0.0.0.0"
    depends_on:
      - django-web
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
  android_sdk:
  flutter_pub_cache:
  gradle_cache: