# Generated by Django 5.2.12 on 2026-03-23 12:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipus', models.CharField(choices=[('treballador', 'Treballador'), ('empresa', 'Empresa')], default=None, max_length=20)),
                ('loginField', models.CharField(max_length=150, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Usuari',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='nom', max_length=100)),
                ('data_inici', models.DateField(db_column='data_inici')),
                ('data_prev_fi', models.DateField(db_column='data_prev_fi')),
                ('data_fi', models.DateField(blank=True, db_column='data_fi', null=True)),
                ('pressupost', models.BigIntegerField(db_column='pressupost')),
                ('descripcio', models.TextField(blank=True, db_column='descripcio', null=True)),
                ('estat', models.CharField(db_column='estat', max_length=50)),
            ],
            options={
                'db_table': 'obra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Permis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clau_funcional', models.CharField(max_length=100, unique=True)),
                ('descripcio', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'permis',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recurs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=120)),
                ('unitats_mesura', models.CharField(max_length=40)),
                ('quantitat_stock', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipus_recurs', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'recurs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ubicacio',
            fields=[
                ('id_ubicacio', models.AutoField(db_column='id_ubicacio', primary_key=True, serialize=False)),
                ('adreca', models.CharField(blank=True, db_column='adreça', max_length=150, null=True)),
                ('ciutat', models.CharField(blank=True, max_length=50, null=True)),
                ('codi_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(db_column='país', default='Espanya', max_length=50)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
            ],
            options={
                'db_table': 'ubicacio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Treballador',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='treballador', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom', models.CharField(max_length=50)),
                ('cognoms', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('dni_nie_passaport', models.CharField(max_length=20, unique=True)),
                ('data_naixement', models.DateField(blank=True, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_treballadors/')),
                ('comentaris', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'treballador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(db_column='id_empresa', primary_key=True, serialize=False)),
                ('nom_empresa', models.CharField(max_length=100)),
                ('cif', models.CharField(max_length=20, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('web', models.URLField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('data_alta', models.DateField(auto_now_add=True)),
                ('estat', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('suspesa', 'Suspesa')], default='activa', max_length=20)),
                ('persona_contacte', models.CharField(blank=True, max_length=100, null=True)),
                ('comentaris', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
                ('ubicacio', models.ForeignKey(blank=True, db_column='ubicacio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empreses', to='apiApp.ubicacio')),
            ],
            options={
                'db_table': 'empresa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcio', models.TextField()),
                ('data_inici', models.DateField()),
                ('data_fi', models.DateField(blank=True, null=True)),
                ('criticitat', models.IntegerField()),
                ('prioritat', models.IntegerField()),
                ('categoria', models.IntegerField()),
                ('estat', models.CharField(max_length=40)),
                ('id_obra', models.ForeignKey(db_column='id_obra', on_delete=django.db.models.deletion.CASCADE, related_name='incidencies', to='apiApp.obra')),
            ],
            options={
                'db_table': 'incidencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentObra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_creador', models.IntegerField()),
                ('path_doc', models.TextField()),
                ('format', models.CharField(max_length=40)),
                ('mida', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comentari', models.TextField(blank=True, null=True)),
                ('data_pujada', models.DateTimeField()),
                ('tipus', models.CharField(max_length=40)),
                ('id_obra', models.ForeignKey(db_column='id_obra', on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='apiApp.obra')),
            ],
            options={
                'db_table': 'document_obra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ObraEmpresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_i', models.DateTimeField()),
                ('data_f', models.DateTimeField(blank=True, null=True)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='relacions_obra', to='apiApp.empresa')),
                ('id_obra', models.ForeignKey(db_column='id_obra', on_delete=django.db.models.deletion.CASCADE, related_name='relacions_empresa', to='apiApp.obra')),
            ],
            options={
                'db_table': 'obra_empresa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SolRecurs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantitat', models.IntegerField()),
                ('data_necessitat', models.DateField()),
                ('comentari', models.TextField(blank=True, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('data_creacio', models.DateTimeField()),
                ('proveidor', models.CharField(blank=True, max_length=120, null=True)),
                ('id_obra', models.ForeignKey(db_column='id_obra', on_delete=django.db.models.deletion.DO_NOTHING, to='apiApp.obra')),
                ('id_recurs', models.ForeignKey(db_column='id_recurs', on_delete=django.db.models.deletion.DO_NOTHING, to='apiApp.recurs')),
            ],
            options={
                'db_table': 'sol_recurs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tasca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcio', models.TextField()),
                ('data_inici', models.DateField()),
                ('data_fi', models.DateField(blank=True, null=True)),
                ('prioritat', models.IntegerField()),
                ('visibilitat_tasca', models.BooleanField(default=True)),
                ('id_obra', models.ForeignKey(db_column='id_obra', on_delete=django.db.models.deletion.CASCADE, related_name='tasques', to='apiApp.obra')),
                ('id_tasca_pare', models.ForeignKey(blank=True, db_column='id_tasca_pare', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiApp.tasca')),
            ],
            options={
                'db_table': 'tasca',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Solucio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcio', models.TextField()),
                ('cost_monetari', models.BigIntegerField()),
                ('eficacia', models.IntegerField()),
                ('cost_temporal', models.IntegerField()),
                ('impacte', models.IntegerField()),
                ('id_incidencia', models.ForeignKey(db_column='id_incidencia', on_delete=django.db.models.deletion.CASCADE, to='apiApp.incidencia')),
                ('id_tasca', models.ForeignKey(blank=True, db_column='id_tasca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apiApp.tasca')),
            ],
            options={
                'db_table': 'solucio',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='incidencia',
            name='id_tasca',
            field=models.ForeignKey(blank=True, db_column='id_tasca', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiApp.tasca'),
        ),
        migrations.AddField(
            model_name='obra',
            name='ubicacio',
            field=models.ForeignKey(db_column='ubicacio_id', on_delete=django.db.models.deletion.CASCADE, related_name='obres', to='apiApp.ubicacio'),
        ),
        migrations.CreateModel(
            name='Verificacio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estat_ver', models.CharField(max_length=40)),
                ('data_ver', models.DateField(blank=True, null=True)),
                ('token_verificacio', models.CharField(max_length=120)),
                ('data_token', models.DateTimeField()),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='apiApp.empresa')),
            ],
            options={
                'db_table': 'verificacio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResponsableObra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inici', models.DateField()),
                ('data_fi', models.DateField(blank=True, null=True)),
                ('id_obra', models.ForeignKey(db_column='id_obra', on_delete=django.db.models.deletion.DO_NOTHING, to='apiApp.obra')),
                ('id_treballador', models.ForeignKey(db_column='id_treballador', on_delete=django.db.models.deletion.DO_NOTHING, to='apiApp.treballador')),
            ],
            options={
                'db_table': 'responsable_obra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PermisTreballador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lectura', models.BooleanField(default=False)),
                ('escriptura', models.BooleanField(default=False)),
                ('edicio', models.BooleanField(default=False)),
                ('data_creacio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_modif', models.DateTimeField(blank=True, null=True)),
                ('id_permis', models.ForeignKey(db_column='id_permis', on_delete=django.db.models.deletion.RESTRICT, to='apiApp.permis')),
                ('id_treballador', models.ForeignKey(db_column='id_treballador', on_delete=django.db.models.deletion.CASCADE, to='apiApp.treballador')),
            ],
            options={
                'db_table': 'permis_treballador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TascaTreballador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentari', models.TextField(blank=True, null=True)),
                ('id_tasca', models.ForeignKey(db_column='id_tasca', on_delete=django.db.models.deletion.CASCADE, to='apiApp.tasca')),
                ('id_treballador', models.ForeignKey(db_column='id_treballador', on_delete=django.db.models.deletion.DO_NOTHING, to='apiApp.treballador')),
            ],
            options={
                'db_table': 'tasca_treballador',
                'managed': True,
                'unique_together': {('id_tasca', 'id_treballador')},
            },
        ),
        migrations.CreateModel(
            name='LogDeSessio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inici', models.DateField()),
                ('hora_inici', models.TimeField()),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiApp.empresa')),
                ('id_treballador', models.ForeignKey(blank=True, db_column='id_treballador', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiApp.treballador')),
            ],
            options={
                'db_table': 'log_de_sessio',
                'managed': True,
                'constraints': [models.CheckConstraint(condition=models.Q(('id_treballador__isnull', False), ('id_empresa__isnull', False), _connector='XOR'), name='chk_log_subjecte')],
            },
        ),
        migrations.CreateModel(
            name='Contrasenya',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clau', models.CharField(max_length=255)),
                ('data_creacio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_reemplas', models.DateTimeField(blank=True, null=True)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.CASCADE, to='apiApp.empresa')),
                ('id_treballador', models.ForeignKey(blank=True, db_column='id_treballador', null=True, on_delete=django.db.models.deletion.CASCADE, to='apiApp.treballador')),
            ],
            options={
                'db_table': 'contrasenya',
                'managed': True,
                'indexes': [models.Index(condition=models.Q(('data_reemplas__isnull', True)), fields=['id_empresa'], name='idx_pwd_e_vigent'), models.Index(condition=models.Q(('data_reemplas__isnull', True)), fields=['id_treballador'], name='idx_pwd_t_vigent')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('id_treballador__isnull', False), ('id_empresa__isnull', True)), models.Q(('id_treballador__isnull', True), ('id_empresa__isnull', False)), _connector='OR'), name='chk_un_fk')],
            },
        ),
        migrations.CreateModel(
            name='ContracteTreballador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_contracte', models.DateField(blank=True, null=True)),
                ('data_fi', models.DateField(blank=True, null=True)),
                ('salari', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carrec', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria_professional', models.CharField(blank=True, max_length=50, null=True)),
                ('nss', models.CharField(blank=True, max_length=20, null=True)),
                ('formacions', models.TextField(blank=True, null=True)),
                ('estat', models.CharField(choices=[('actiu', 'Actiu'), ('baixa', 'Baixa'), ('acomiadat', 'Acomiadat')], default='actiu', max_length=20)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.RESTRICT, to='apiApp.empresa')),
                ('id_treballador', models.ForeignKey(db_column='id_treballador', on_delete=django.db.models.deletion.RESTRICT, to='apiApp.treballador')),
            ],
            options={
                'db_table': 'contracte_treballador',
                'managed': True,
                'unique_together': {('id_treballador', 'data_contracte')},
            },
        ),
        migrations.CreateModel(
            name='Configuracio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idioma', models.CharField(blank=True, default='ca', max_length=10, null=True)),
                ('acceptacio_terms', models.BooleanField(default=False)),
                ('imatge_perfil', models.CharField(blank=True, max_length=255, null=True)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.CASCADE, to='apiApp.empresa')),
                ('id_treballador', models.ForeignKey(blank=True, db_column='id_treballador', null=True, on_delete=django.db.models.deletion.CASCADE, to='apiApp.treballador')),
            ],
            options={
                'db_table': 'configuracio',
                'managed': True,
                'constraints': [models.CheckConstraint(condition=models.Q(('id_treballador__isnull', False), ('id_empresa__isnull', False), _connector='XOR'), name='chk_cfg_subjecte'), models.UniqueConstraint(condition=models.Q(('id_treballador__isnull', False)), fields=('id_treballador',), name='ux_cfg_treballador_one'), models.UniqueConstraint(condition=models.Q(('id_empresa__isnull', False)), fields=('id_empresa',), name='ux_cfg_empresa_one')],
            },
        ),
    ]
