# Generated by Django 4.2.17 on 2025-08-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idioma', models.CharField(blank=True, default='ca', max_length=10, null=True)),
                ('acceptacio_terms', models.BooleanField(default=False)),
                ('imatge_perfil', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'configuracio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContracteTreballador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_contracte', models.DateField(blank=True, null=True)),
                ('data_fi', models.DateField(blank=True, null=True)),
                ('salari', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carrec', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria_professional', models.CharField(blank=True, max_length=50, null=True)),
                ('nss', models.CharField(blank=True, max_length=20, null=True)),
                ('formacions', models.TextField(blank=True, null=True)),
                ('estat', models.CharField(choices=[('actiu', 'Actiu'), ('baixa', 'Baixa'), ('acomiadat', 'Acomiadat')], default='actiu', max_length=20)),
            ],
            options={
                'db_table': 'contracte_treballador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrasenya',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clau', models.CharField(max_length=255)),
                ('data_creacio', models.DateTimeField()),
                ('data_reemplas', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contrasenya',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentObra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_creador', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=160)),
                ('format', models.CharField(max_length=40)),
                ('mida', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comentari', models.TextField(blank=True, null=True)),
                ('data_pujada', models.DateTimeField()),
                ('tipus', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'document_obra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(db_column='id_empresa', primary_key=True, serialize=False)),
                ('nom_empresa', models.CharField(max_length=100)),
                ('cif', models.CharField(max_length=20, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('web', models.URLField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('data_alta', models.DateField(auto_now_add=True)),
                ('num_empleats', models.IntegerField(blank=True, db_column='num_empleats', null=True)),
                ('estat', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('suspesa', 'Suspesa')], default='activa', max_length=20)),
                ('persona_contacte', models.CharField(blank=True, max_length=100, null=True)),
                ('comentaris', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcio', models.TextField()),
                ('data_inici', models.DateField()),
                ('data_fi', models.DateField(blank=True, null=True)),
                ('criticitat', models.IntegerField()),
                ('prioritat', models.IntegerField()),
                ('categoria', models.IntegerField()),
                ('estat', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'incidencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogDeSessio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inici', models.DateField()),
                ('hora_inici', models.TimeField()),
            ],
            options={
                'db_table': 'log_de_sessio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='nom', max_length=100)),
                ('ubicacio', models.CharField(db_column='ubicacio', max_length=255)),
                ('data_inici', models.DateField(db_column='data_inici')),
                ('data_prev_fi', models.DateField(db_column='data_prev_fi')),
                ('data_fi', models.DateField(blank=True, db_column='data_fi', null=True)),
                ('pressupost', models.BigIntegerField(db_column='pressupost')),
                ('descripcio', models.TextField(blank=True, db_column='descripcio', null=True)),
                ('estat', models.CharField(db_column='estat', max_length=50)),
            ],
            options={
                'db_table': 'obra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clau_funcional', models.CharField(max_length=100, unique=True)),
                ('descripcio', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'permis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermisTreballador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lectura', models.BooleanField()),
                ('escriptura', models.BooleanField()),
                ('edicio', models.BooleanField()),
                ('data_creacio', models.DateTimeField()),
                ('data_modif', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'permis_treballador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recurs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=120)),
                ('unitats_mesura', models.CharField(max_length=40)),
                ('quantitat_stock', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipus_recurs', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'recurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsableObra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inici', models.DateField()),
                ('data_fi', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'responsable_obra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolRecurs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantitat', models.IntegerField()),
                ('data_necessitat', models.DateField()),
                ('comentari', models.TextField(blank=True, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('data_creacio', models.DateTimeField()),
                ('proveidor', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'sol_recurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solucio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcio', models.TextField()),
                ('cost_monetari', models.BigIntegerField()),
                ('eficacia', models.IntegerField()),
                ('cost_temporal', models.IntegerField()),
                ('impacte', models.IntegerField()),
            ],
            options={
                'db_table': 'solucio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcio', models.TextField()),
                ('data_inici', models.DateField()),
                ('data_fi', models.DateField(blank=True, null=True)),
                ('prioritat', models.IntegerField()),
                ('visibilitat_tasca', models.BooleanField()),
            ],
            options={
                'db_table': 'tasca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TascaTreballador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentari', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tasca_treballador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treballador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('cognoms', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('dni_nie_passaport', models.CharField(max_length=20, unique=True)),
                ('data_naixement', models.DateField(blank=True, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_treballadors/')),
                ('comentaris', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'treballador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacio',
            fields=[
                ('id', models.AutoField(db_column='id_ubicacio', primary_key=True, serialize=False)),
                ('adreca', models.CharField(blank=True, db_column='adreça', max_length=150, null=True)),
                ('ciutat', models.CharField(blank=True, max_length=50, null=True)),
                ('codi_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(db_column='país', default='Espanya', max_length=50)),
            ],
            options={
                'db_table': 'ubicacio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Verificacio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estat_ver', models.CharField(max_length=40)),
                ('data_ver', models.DateField(blank=True, null=True)),
                ('token_verificacio', models.CharField(max_length=120)),
                ('data_token', models.DateTimeField()),
            ],
            options={
                'db_table': 'verificacio',
                'managed': False,
            },
        ),
    ]
