# Generated by Django 4.2.17 on 2025-05-03 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Ubicacio', models.CharField(max_length=200, null=True)),
                ('Data_inici', models.DateField(default=django.utils.timezone.now)),
                ('Data_prev_fi', models.DateField(null=True)),
                ('Pressupost', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Descripcio', models.TextField(blank=True, null=True)),
                ('Estat', models.CharField(default='Res Firmat', max_length=50)),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obres',
                'ordering': ['Nom'],
            },
        ),
    ]
