# Generated by Django 5.2.12 on 2026-03-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuari',
            table='usuari',
        ),
    ]
