# Generated by Django 4.2.17 on 2025-07-04 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiappObra',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='Nom', max_length=100)),
                ('ubicacio', models.CharField(blank=True, db_column='Ubicacio', max_length=200, null=True)),
                ('data_inici', models.DateField(db_column='Data_inici')),
                ('data_prev_fi', models.DateField(blank=True, db_column='Data_prev_fi', null=True)),
                ('pressupost', models.DecimalField(blank=True, db_column='Pressupost', decimal_places=2, max_digits=12, null=True)),
                ('descripcio', models.TextField(blank=True, db_column='Descripcio', null=True)),
                ('estat', models.CharField(db_column='Estat', max_length=50)),
            ],
            options={
                'db_table': 'apiApp_obra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrasenya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clau', models.CharField(max_length=255)),
                ('data_creacio', models.DateTimeField()),
                ('data_reemplas', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contrasenya',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=160)),
                ('format', models.CharField(max_length=40)),
                ('mida', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('comentari', models.TextField(blank=True, null=True)),
                ('data_pujada', models.DateTimeField()),
                ('tipus', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'document_obra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcio', models.TextField()),
                ('data_inici', models.DateField()),
                ('data_fi', models.DateField(blank=True, null=True)),
                ('criticitat', models.IntegerField()),
                ('prioritat', models.IntegerField()),
                ('categoria', models.IntegerField()),
                ('estat', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'incidencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogDeSessio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inici', models.DateField()),
                ('hora_inici', models.TimeField()),
            ],
            options={
                'db_table': 'log_de_sessio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clau_funcional', models.CharField(max_length=100, unique=True)),
                ('descripcio', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'permis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermisUsuari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectura', models.BooleanField()),
                ('escriptura', models.BooleanField()),
                ('edicio', models.BooleanField()),
                ('data_creacio', models.DateTimeField()),
                ('data_modif', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'permis_usuari',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('unitats_mesura', models.CharField(max_length=40)),
                ('quantitat_stock', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('tipus_recurs', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'recurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsableObra',
            fields=[
                ('id_obra', models.OneToOneField(db_column='id_obra', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='apiApp.obra')),
                ('data_inici', models.DateField()),
                ('data_fi', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'responsable_obra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolRecurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.IntegerField()),
                ('data_necessitat', models.DateField()),
                ('comentari', models.TextField(blank=True, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('data_creacio', models.DateTimeField()),
                ('proveidor', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'sol_recurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solucio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcio', models.TextField()),
                ('cost_monetari', models.BigIntegerField()),
                ('eficacia', models.IntegerField()),
                ('cost_temporal', models.IntegerField()),
                ('impacte', models.IntegerField()),
            ],
            options={
                'db_table': 'solucio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcio', models.TextField()),
                ('data_inici', models.DateField()),
                ('data_fi', models.DateField(blank=True, null=True)),
                ('prioritat', models.IntegerField()),
                ('visibilitat_tasca', models.BooleanField()),
            ],
            options={
                'db_table': 'tasca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.TextField()),
                ('nom', models.CharField(max_length=120)),
                ('cognoms', models.CharField(max_length=160)),
                ('rol', models.CharField(max_length=60)),
                ('telefon', models.BigIntegerField(blank=True, null=True)),
                ('estat', models.CharField(max_length=40)),
                ('data_creacio', models.DateTimeField()),
            ],
            options={
                'db_table': 'usuari',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Verificacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estat_ver', models.CharField(max_length=40)),
                ('data_ver', models.DateField(blank=True, null=True)),
                ('token_verificacio', models.CharField(max_length=120)),
                ('data_token', models.DateTimeField()),
            ],
            options={
                'db_table': 'verificacio',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='obra',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='Configuracio',
            fields=[
                ('id_usuari', models.OneToOneField(db_column='id_usuari', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='apiApp.usuari')),
                ('idioma', models.CharField(blank=True, max_length=10, null=True)),
                ('acceptacio_terms', models.BooleanField()),
                ('imatge_perfil', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'configuracio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TascaTreballador',
            fields=[
                ('id_tasca', models.OneToOneField(db_column='id_tasca', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='apiApp.tasca')),
                ('comentari', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tasca_treballador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UEmpresa',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='apiApp.usuari')),
                ('correu', models.CharField(max_length=160)),
                ('identificador', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'u_empresa',
                'managed': False,
            },
        ),
    ]
