# Generated by Django 4.2.17 on 2025-07-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_apiappobra_authgroup_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='obra',
            table='obra',
        ),
    ]
