# Generated by Django 4.2.17 on 2025-07-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_alter_obra_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiappObra',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AlterModelTable(
            name='configuracio',
            table='CONFIGURACIO',
        ),
        migrations.AlterModelTable(
            name='contrasenya',
            table='CONTRASENYA',
        ),
        migrations.AlterModelTable(
            name='documentobra',
            table='DOCUMENT_OBRA',
        ),
        migrations.AlterModelTable(
            name='incidencia',
            table='INCIDENCIA',
        ),
        migrations.AlterModelTable(
            name='logdesessio',
            table='LOG_SESSIO',
        ),
        migrations.AlterModelTable(
            name='obra',
            table='OBRA',
        ),
        migrations.AlterModelTable(
            name='permis',
            table='PERMIS',
        ),
        migrations.AlterModelTable(
            name='permisusuari',
            table='PERMIS_USUARI',
        ),
        migrations.AlterModelTable(
            name='recurs',
            table='RECURS',
        ),
        migrations.AlterModelTable(
            name='responsableobra',
            table='RESPONSABLE_OBRA',
        ),
        migrations.AlterModelTable(
            name='solrecurs',
            table='SOL_RECURS',
        ),
        migrations.AlterModelTable(
            name='solucio',
            table='SOLUCIO',
        ),
        migrations.AlterModelTable(
            name='tasca',
            table='TASCA',
        ),
        migrations.AlterModelTable(
            name='tascatreballador',
            table='TASCA_TREBALLADOR',
        ),
        migrations.AlterModelTable(
            name='uempresa',
            table='U_EMPRESA',
        ),
        migrations.AlterModelTable(
            name='usuari',
            table='USUARI',
        ),
        migrations.AlterModelTable(
            name='verificacio',
            table='VERIFICACIO',
        ),
    ]
