# Generated by Django 4.2.17 on 2025-07-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0007_alter_configuracio_options_alter_contrasenya_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracio',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contrasenya',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='documentobra',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='incidencia',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='logdesessio',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='obra',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='permis',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='permisusuari',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='recurs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='responsableobra',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='solrecurs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='solucio',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tasca',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tascatreballador',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='uempresa',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='upersona',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuari',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='verificacio',
            options={'managed': False},
        ),
    ]
