# Generated by Django 4.2.17 on 2025-07-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0008_alter_configuracio_options_alter_contrasenya_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upersona',
            options={'managed': True},
        ),
    ]
